baseURL = "https://mattdrake.dev"
languageCode = "en-us"
theme = "cocoa"
contentdir = "content"
publishdir = "public"
author = "Matt Drake"
title = "Matt Drake"
pygmentsUseClasses = true
pygmentsCodefences = true


[permalinks]
blog = "blog/:slug/"

[[menu.main]]
name = "Blog"
weight = -130
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Projects"
weight = -120
identifier = "projects"
url = "/fixed/projects"

[[menu.main]]
name = "About"
weight = -110
identifier = "about"
url = "/fixed/about"

[[menu.main]]
name = "GitHub"
weight = -100
url = "https://github.com/drake6m"

[[menu.main]]
name = "Twitter"
weight = -90
url = "https://twitter.com/drake6m"

[params]
latestpostscount = 30
author = "Matt Drake"
dateform = "2 Jan 2006"
avatar = "img/avatar-min.jpg"
noshowreadtime = true
github = "//github.com/drake6m"
twitter = "//twitter.com/drake6m"
afterPostBlurb = ""
cachebuster = true
